version: '3'

services:
  python:
    image: "python:3"
    volumes:
      - .:/home/root
    ports:
      - 800:800
    stdin_open: true
    tty: true
  noje_js:
    image: heroku/nodejs-hello-world
    ports:
      - 801:3000
